server:
   port: 8081
   
spring:
   application:
      name: provider
eureka:
   client:
      service-url:
         defaultZone: http://localhost:9010/eureka/
         
management:
  endpoints:
    web:
      exposure:
        include: "*"