version: '3'

# docker run -d --name=jenkins --net=hub0 -p 8080:8080 50000:50000 -v Z:/volumes/jenkins:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock jenkins/jenkins
# docker run -d --name=gitlib --net=hub0 -p 80:80 --restart always gitlab/gitlab-ce
# docker run -d --net=hub0 -p 5000:5000 --name registry registry

services:

    jenkins:
        image: jenkins/jenkins
        ports:
            - 9001:8080
        volumes:   
            - Z:/volumes/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            
    gitlib:
        image: gitlab/gitlab-ce
        ports:
            - 9002:80
        
    
    registry:
        image: registry
        ports:
            - 5000:5000